### ISSUE TITLE
Implement new design from Library Communications

### ISSUE THREAD

**Issue by axamei** [pulibrary/recap#106]
https://drive.google.com/drive/folders/1uEKH7LRcqo8sFn-Fq8MykGijlZ1w3p-E

**Comment by kevinreiss** [comment]
After reviewing my conversation with Stephanie, we should feel free to have some license to size the text for maximum readability on the web since the fonts in the PDF provided are tiny. There will need to be three templates:

1. Homepage (different only from top-level page because it includes the twitter block)
2. Top level page, need left aligned pinwheel with picture and right aligned pinwheel w/o image as a background graphic.
3. Second level page, left aligned pinwheel as background graphic.

**Comment by axamei** [comment]
On prod
